return {
  code = {
    File = "⨏",
    Module = "M",
    Namespace = "N",
    Package = "P",
    Class = "𝓒",
    Method ="m",
    Property ="p",
    Field = "⨍",
    Constructor = "",
    Enum = "ℰ",
    Interface = "ℹ",
    Function = "λ",
    Variable = "v",
    Constant = "c",
    String = "s",
    Number = "#",
    Boolean = "⊨",
    Array = "a",
    Object = "⦿",
    Key = "🔐",
    Null = "NULL",
    EnumMember = "ℰm",
    Struct = "𝓢",
    Event = "🗲",
    Operator = "+",
    TypeParameter = "𝙏",
    Text = "txt",
    Unit = "u",
    Value = "val",
    Keyword = "K",
    Snippet = "~",
    Color = "color",
    Reference = "r",
    Folder = "📁",
  }
}
