return {
  code = {
    File = "📄",
    Module = "𝚺",
    Namespace = "n",
    Package = "📦",
    Class = "∁",
    Method ="m",
    Property ="p",
    Field = "⨍",
    Constructor = "👷",
    Enum = "ℰ",
    Interface = "ℹ",
    Function = "λ",
    Variable = "𝒗",
    Constant = "c",
    String = "s",
    Number = "#",
    Boolean = "⌥",
    Array = "ä",
    Object = "⦿",
    Key = "k",
    Null = "NULL",
    EnumMember = "ℰm",
    Struct = "𝓢",
    Event = "🗲",
    Operator = "∓",
    TypeParameter = "𝙏",
    Text = "📑",
    Unit = "u",
    Value = "val",
    Keyword = "🔑",
    Snippet = "<>",
    Color = "color",
    Reference = "※",
    Folder = "📂",
  },
}

